
#pragma once
#include <string>

const std::string
    GAME_NAME = "SPACE CONQUEST!";

const unsigned int
    WINDOW_WIDTH = 1600,
    WINDOW_HEIGHT = 880;

const float
    FRAME_LIMIT = 60.f,
    FRAME_TIME = 1.f / 60.f,
    WINDOW_BORDER = 60.f,
    POWERUP_SCALE = 5.f;

const int
    SCORE_FONT_SIZE = 50,
    TIMER_FONT_SIZE = 60,
    PROMPT_FONT_SIZE = 100,
    RESULTS_GAME_OVER_FONT_SIZE = 60,
    RESULTS_WINNER_FONT_SIZE = 200,
    RESULTS_SCORE_FONT_SIZE = 80,
    RESULTS_BREAKDOWN_FONT_SIZE = 32,
    TITLE_FONT_SIZE = 250,
    ESCAPE_FONT_SIZE = 40,
    MAP_SELECT_FONT_SIZE = 50;

const sf::Vector2f 
    PLAYER_SCORE_POSITION = {10.f, 0.f},
    ENEMY_SCORE_POSITION = {10.f, 50.f},
    TIMER_UI_POSITION = {WINDOW_WIDTH - 175.f, 0.f},
    PROMPT_POSITION = {WINDOW_WIDTH / 2.f, WINDOW_HEIGHT - (WINDOW_HEIGHT / 4.f)},
    TITLE_POSITION = {WINDOW_WIDTH / 2.f, WINDOW_HEIGHT / 3.f};
    
const sf::Vector2f
    RESULTS_WINNER_CENTER = {WINDOW_WIDTH / 2.f, WINDOW_HEIGHT / 4.f};

const float
    RESULTS_GAME_OVER_OFFSET = -100,
    RESULTS_SCORE_OFFSET = 150,
    RESULTS_BREAKDOWN_OFFSET = 65,
    RESULTS_BREAKDOWN_PADDING = 35,
    MAIN_MENU_ESCAPE_OFFSET = 80,
    MAP_SELECT_OFFSET = -80;
